spring:
  application:
    name: crud
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres"
    name: springDatasource
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      plataform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml